name: build-ami

env:
  AWS_REGION: us-east-1

on:
  push:
    branches: [main]

jobs:
  AMI_build_Raj:
    if: github.actor == 'rajmehta53'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Build the AMI
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: base_ami.json
        env: 
          remote_account_id: ${{ secrets.REMOTE_ID }}
          
  AMI_build_Bhan:
    if: github.actor == 'Bh-an'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_BHAN }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_BHAN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Build the AMI
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: base_ami.json